[tool.poetry]
name = "personal_portfolio"
version = "0.1.0"
description = "My personal portfolio"
authors = ["Keith Riordan <keith.riordan@gmail.com>"]

[tool.poetry.dependencies]
python = "3.11"
Flask = "^2.1.3"
Flask-SQLAlchemy = "^3.0.2"
boto3 = "^1.24.41"
python-dotenv = "^0.21.0"
APScheduler = "^3.9.1"
requests = "^2.28.1"
PyYAML = "^6.0"
sendgrid = "^6.9.7"
Flask-WTF = "^1.0.1"
email-validator = "^1.2.1"
psycopg2 = "^2.9.3"
flask-login = "^0.6.2"
sqlalchemy-utils = "^0.39.0"
flask-migrate = "^4.0.0"
flask-bcrypt = "^1.0.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
djlint = "^1.19.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
