import os


WTF_CSRF_ENABLED = True

SECRET_KEY = os.getenv('SECRET_KEY')

SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL')
SQLALCHEMY_TRACK_MODIFICATIONS = True

S3_BUCKET = os.getenv('S3_BUCKET')

DEBUG = False
