"""Add HLR fields

Revision ID: 01b6b2a3c6ef
Revises: 9e5947e5a52a
Create Date: 2026-01-22 20:44:15.337952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b6b2a3c6ef'
down_revision = '9e5947e5a52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('half_life_before', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('half_life_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('predicted_recall_before', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('predicted_recall_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_recall', sa.Float(), nullable=True))

    with op.batch_alter_table('review_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('half_life_days', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_recall', sa.Float(), nullable=False, server_default='0.9'))
        batch_op.add_column(sa.Column('predicted_recall', sa.Float(), nullable=True))
        batch_op.alter_column('target_recall', server_default=None)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduler_preference', sa.String(length=32), nullable=False, server_default='sm2_v2_steps'))
        batch_op.alter_column('scheduler_preference', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('scheduler_preference')

    with op.batch_alter_table('review_progress', schema=None) as batch_op:
        batch_op.drop_column('predicted_recall')
        batch_op.drop_column('target_recall')
        batch_op.drop_column('half_life_days')

    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.drop_column('target_recall')
        batch_op.drop_column('predicted_recall_after')
        batch_op.drop_column('predicted_recall_before')
        batch_op.drop_column('half_life_after')
        batch_op.drop_column('half_life_before')

    # ### end Alembic commands ###
