"""Use timezone-aware timestamps

Revision ID: 10ddbb79dd15
Revises: c3d4e5f6a7b8
Create Date: 2026-01-16 15:32:47.325483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10ddbb79dd15'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_list', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('email_verification_attempt', schema=None) as batch_op:
        batch_op.alter_column('attempted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="attempted_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="timestamp AT TIME ZONE 'UTC'")

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('posted_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="posted_date AT TIME ZONE 'UTC'")

    with op.batch_alter_table('list_invitation', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('accepted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="accepted_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="expires_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('password_reset_attempt', schema=None) as batch_op:
        batch_op.alter_column('attempted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="attempted_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.alter_column('published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="published_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('site_invitation', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('accepted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="accepted_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="expires_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_verification_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="email_verification_expires_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.alter_column('published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="published_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="published_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_verification_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="email_verification_expires_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('site_invitation', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="expires_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('accepted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="accepted_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               postgresql_using="created_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="published_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('password_reset_attempt', schema=None) as batch_op:
        batch_op.alter_column('attempted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="attempted_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('list_invitation', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="expires_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('accepted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="accepted_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               postgresql_using="created_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('posted_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="posted_date AT TIME ZONE 'UTC'")

    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="timestamp AT TIME ZONE 'UTC'")

    with op.batch_alter_table('email_verification_attempt', schema=None) as batch_op:
        batch_op.alter_column('attempted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="attempted_at AT TIME ZONE 'UTC'")

    with op.batch_alter_table('custom_list', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               postgresql_using="updated_at AT TIME ZONE 'UTC'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               postgresql_using="created_at AT TIME ZONE 'UTC'")

    # ### end Alembic commands ###
