"""Add review progress

Revision ID: 3767349966b5
Revises: 10ddbb79dd15
Create Date: 2026-01-20 21:38:53.330449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3767349966b5'
down_revision = '10ddbb79dd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=128), nullable=False),
    sa.Column('easiness', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_progress_card_id'), ['card_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_progress_card_id'))

    op.drop_table('review_progress')
    # ### end Alembic commands ###
