"""Remove unique constraint from video_url_id

Revision ID: 412d892be13f
Revises: 7596e4ae82a2
Create Date: 2024-08-08 14:52:44.086693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412d892be13f'
down_revision = '7596e4ae82a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint('video_video_url_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_unique_constraint('video_video_url_id_key', ['video_url_id'])

    # ### end Alembic commands ###
