"""Add password reset attempt table

Revision ID: 6ea635fe0a53
Revises: fix_list_item_nullable
Create Date: 2026-01-12 17:15:53.304616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea635fe0a53'
down_revision = 'fix_list_item_nullable'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_attempt_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_attempt_email'))

    op.drop_table('password_reset_attempt')
    # ### end Alembic commands ###
