"""Initial migration

Revision ID: 7596e4ae82a2
Revises: 
Create Date: 2024-08-08 14:40:48.739787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7596e4ae82a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('listing_url', sa.String(), nullable=False),
    sa.Column('listing_image', sa.String(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_updated_at'), ['updated_at'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('image_url', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_user_id'), ['user_id'], unique=False)

    op.create_table('video',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('playlist_id', sa.String(), nullable=False),
    sa.Column('video_url_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('embed_url', sa.String(length=255), nullable=False),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_url_id')
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_playlist_id'), ['playlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_title'))
        batch_op.drop_index(batch_op.f('ix_video_published_at'))
        batch_op.drop_index(batch_op.f('ix_video_playlist_id'))

    op.drop_table('video')
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_user_id'))
        batch_op.drop_index(batch_op.f('ix_gift_timestamp'))

    op.drop_table('gift')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_updated_at'))
        batch_op.drop_index(batch_op.f('ix_playlist_title'))
        batch_op.drop_index(batch_op.f('ix_playlist_published_at'))

    op.drop_table('playlist')
    op.drop_table('jobs')
    # ### end Alembic commands ###
