"""wishlist_items table

Revision ID: 82d0e9daa18c
Revises: 07e1e7fd3e06
Create Date: 2023-12-07 15:49:14.226697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d0e9daa18c'
down_revision = '07e1e7fd3e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_item_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_item_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_item_timestamp'))

    op.drop_table('wishlist_item')
    # ### end Alembic commands ###
