"""Add title to gift

Revision ID: 8ae27db58cde
Revises: aa630e63ed8b
Create Date: 2023-12-12 21:35:54.237558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae27db58cde'
down_revision = 'aa630e63ed8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
