"""Add learning state fields

Revision ID: 9e5947e5a52a
Revises: c48018381e52
Create Date: 2026-01-21 15:46:40.958955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5947e5a52a'
down_revision = 'c48018381e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_state_before', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('learning_state_after', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('step_index_before', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('step_index_after', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lapses_before', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lapses_after', sa.Integer(), nullable=True))

    with op.batch_alter_table('review_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_state', sa.String(length=16), nullable=False, server_default='review'))
        batch_op.add_column(sa.Column('step_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lapses', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_rating', sa.Integer(), nullable=True))
        batch_op.alter_column('learning_state', server_default=None)
        batch_op.alter_column('lapses', server_default=None)

    op.execute("UPDATE review_progress SET scheduler_version = 'sm2_v2_steps'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_progress', schema=None) as batch_op:
        batch_op.drop_column('last_rating')
        batch_op.drop_column('lapses')
        batch_op.drop_column('step_index')
        batch_op.drop_column('learning_state')

    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.drop_column('lapses_after')
        batch_op.drop_column('lapses_before')
        batch_op.drop_column('step_index_after')
        batch_op.drop_column('step_index_before')
        batch_op.drop_column('learning_state_after')
        batch_op.drop_column('learning_state_before')

    # ### end Alembic commands ###
