"""Add review log and scheduler version

Revision ID: c48018381e52
Revises: 3767349966b5
Create Date: 2026-01-21 11:00:27.124087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48018381e52'
down_revision = '3767349966b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=128), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('scheduler_version', sa.String(length=32), nullable=False),
    sa.Column('interval_before', sa.Integer(), nullable=False),
    sa.Column('easiness_before', sa.Float(), nullable=False),
    sa.Column('repetitions_before', sa.Integer(), nullable=False),
    sa.Column('next_review_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_after', sa.Integer(), nullable=False),
    sa.Column('easiness_after', sa.Float(), nullable=False),
    sa.Column('repetitions_after', sa.Integer(), nullable=False),
    sa.Column('next_review_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_log_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_log_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('review_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduler_version', sa.String(length=32), nullable=False, server_default='sm2_v1'))
        batch_op.alter_column('scheduler_version', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_progress', schema=None) as batch_op:
        batch_op.drop_column('scheduler_version')

    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_log_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_review_log_card_id'))

    op.drop_table('review_log')
    # ### end Alembic commands ###
