from datetime import timedelta

MINUTE = 60
DAY = 60 * 60 * 24

SCHEDULER_VERSION = "sm2_v2_steps"

LEARNING_STEPS = [timedelta(minutes=10), timedelta(days=1)]
RELEARNING_STEPS = [timedelta(minutes=10), timedelta(days=1)]

GRADUATING_INTERVAL_DAYS = 3
POST_LAPSE_INTERVAL_DAYS = 1
MIN_EASINESS = 1.3

# HLR config
HLR_SCHEDULER_VERSION = "hlr_v1"
HLR_INITIAL_HALF_LIFE = 0.5
HLR_MIN_HALF_LIFE = 0.01
HLR_MAX_HALF_LIFE = 365.0
HLR_MIN_INTERVAL_HOURS = 1
HLR_DEFAULT_TARGET_RECALL = 0.9
HLR_HALF_LIFE_MULTIPLIERS = {3: 1.4, 4: 1.8, 5: 2.2}
HLR_LAPSE_MULTIPLIER = 0.5
